/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const MedicineId = IDL.Nat;
export const SectionName = IDL.Text;
export const Medicine = IDL.Record({
  'id' : MedicineId,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : IDL.Text,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addMedicine' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [MedicineId],
      [],
    ),
  'deleteMedicine' : IDL.Func([MedicineId], [], []),
  'editMedicine' : IDL.Func(
      [MedicineId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
      [],
      [],
    ),
  'getAllContent' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(SectionName, IDL.Text))],
      ['query'],
    ),
  'getAvailableMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'getContent' : IDL.Func([SectionName], [IDL.Text], ['query']),
  'getMedicalProduct' : IDL.Func([MedicineId], [Medicine], ['query']),
  'getMedicinesByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Medicine)],
      ['query'],
    ),
  'getMedicinesSortedByPrice' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'listMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
  'searchMedicines' : IDL.Func([IDL.Text], [IDL.Vec(Medicine)], ['query']),
  'updateContent' : IDL.Func([SectionName, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const MedicineId = IDL.Nat;
  const SectionName = IDL.Text;
  const Medicine = IDL.Record({
    'id' : MedicineId,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : IDL.Text,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'addMedicine' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [MedicineId],
        [],
      ),
    'deleteMedicine' : IDL.Func([MedicineId], [], []),
    'editMedicine' : IDL.Func(
        [MedicineId, IDL.Text, IDL.Text, IDL.Nat, IDL.Text, IDL.Bool],
        [],
        [],
      ),
    'getAllContent' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(SectionName, IDL.Text))],
        ['query'],
      ),
    'getAvailableMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'getContent' : IDL.Func([SectionName], [IDL.Text], ['query']),
    'getMedicalProduct' : IDL.Func([MedicineId], [Medicine], ['query']),
    'getMedicinesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Medicine)],
        ['query'],
      ),
    'getMedicinesSortedByPrice' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'listMedicines' : IDL.Func([], [IDL.Vec(Medicine)], ['query']),
    'searchMedicines' : IDL.Func([IDL.Text], [IDL.Vec(Medicine)], ['query']),
    'updateContent' : IDL.Func([SectionName, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };