/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Medicine {
  'id' : MedicineId,
  'name' : string,
  'description' : string,
  'available' : boolean,
  'category' : string,
  'price' : bigint,
}
export type MedicineId = bigint;
export type SectionName = string;
export interface _SERVICE {
  'addMedicine' : ActorMethod<[string, string, bigint, string], MedicineId>,
  'deleteMedicine' : ActorMethod<[MedicineId], undefined>,
  'editMedicine' : ActorMethod<
    [MedicineId, string, string, bigint, string, boolean],
    undefined
  >,
  'getAllContent' : ActorMethod<[], Array<[SectionName, string]>>,
  'getAvailableMedicines' : ActorMethod<[], Array<Medicine>>,
  'getContent' : ActorMethod<[SectionName], string>,
  'getMedicalProduct' : ActorMethod<[MedicineId], Medicine>,
  'getMedicinesByCategory' : ActorMethod<[string], Array<Medicine>>,
  'getMedicinesSortedByPrice' : ActorMethod<[], Array<Medicine>>,
  'listMedicines' : ActorMethod<[], Array<Medicine>>,
  'searchMedicines' : ActorMethod<[string], Array<Medicine>>,
  'updateContent' : ActorMethod<[SectionName, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];